### ISSUE TITLE
Tables ending in 'o' get pluralized with es

### ISSUE THREAD

**Issue by TheMrAnderson** [bricelam/EFCore.Pluralizer#4]
I have a table called EmployeeInfo and it is pluralized as EmployeeInfoes

**Comment by bricelam** [comment]
I don't intend to fix any issues with the pluralizer itself. It's an exact copy of the EF6 pluralizer and includes all of it's quirks. I like to think if you're porting an app from EF6 to EF Core, using this pluralizer might help reduce the number of changes you need to make in domain logic.

We never fixed the EF6 issues because it was used in Code First any changing the table names would break existing applications.

If you're interested in a better pluralizer, I'd recommend using [Humanizer](https://github.com/Humanizr/Humanizer#inflector-methods).

**Comment by bricelam** [comment]
(Please feel free to fork this repo, swap out the pluralizer, and ship a new package)
